#!/usr/bin/zsh
# .xinitrc for Troels Henriksen <athas@sigkill.dk>

xrdb ~/.Xdefaults

# Accept all connections from the local machine.
xhost +local:

# Disable bell.
xset b off

# Start GNU Emacs and redirect output to a logfile.
u emacs -f on-start >& ~/emacs.log &

# Do some stuff to make my Trackman work properly (I'm not sure how
# this works - it's pure magic.).
xset m 4 25 &
imwheel -k -p -f -b "67" &

# Start a window-manager.
exec xmonad
