# This file is evaluated for all zsh shells.

# This is the path to p9p (but it could probably be 9base too)
export PLAN9=/home/athas/.local/plan9 export PLAN9

export MANPATH="$HOME/.cabal/share/man/:$HOME/.local/share/man/:"

export HOSTTYPE="$(uname -m)"
export COLORTERM=yes
export CC=gcc
export CXX=g++
export MANPAGER=less
export PAGER=less
export EDITOR=emacsclient
export LC_ALL=en_DK.UTF-8
export DARCS_EMAIL="athas@sigkill.dk"
export DARCS_EDITOR="emacsclient"

# XDG is useful, but not very many things respect it.
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
