export red=$'\e[0;31m'
export RED=$'\e[1;31m'
export green=$'\e[0;32m'
export GREEN=$'\e[1;32m'
export blue=$'\e[0;34m'
export BLUE=$'\e[1;34m'
export purple=$'\e[0;35m'
export PURPLE=$'\e[1;35m'
export cyan=$'\e[0;36m'
export CYAN=$'\e[1;36m'
export white=$'\e[0;37m'
export WHITE=$'\e[1;37m'
export yellow=$'\e[0;33m'
export YELLOW=$'\e[01;33m'
export NC=$'\e[0m'
reset=$(tput sgr0)

function precmd {
    typeset e=$?

    (( e )) && echo -n "$RED$e$white$NC"
}

PS1='$(exit_code=$?; [[ $exit_code -eq 0 ]] || printf %s \[$RED\] $exit_code \[$reset\])[\[\033[00;31m\]\h\[\033[00m\]]\[\033[00;32m\]\W\[\033[00m\]>\[\033[01;33m\]\$ \[\033[00m\]'

#Aliases...

alias playmidi="aplaymidi -p 73:0"
alias halt="sudo /sbin/halt"
alias p3="play123"
alias nano="nano -w"
alias clim="/usr/bin/sbcl --eval \"(run-clim-desktop)\""
alias murder="killall -9"

#Other stuff

shopt -s histappend
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

umask 077
export EDITOR=emacsclient
export LC_ALL=en_DK.utf8
export HISTSIZE=""
alias ..='cd ..'
alias ...='.. && ..'
alias ....='... && ..'
alias .....='.... && ..'
alias ......='..... && ..'
alias .......='...... && ..'

PROMPT_COMMAND='echo -ne "\033]0;$(pwd|sed s!^$HOME!~!)\007"'


